### ISSUE TITLE
Does not play on arch/manjaro

### ISSUE THREAD

**Issue by chmol** [marios8543/Jellyfin-CLI#1]
I've just installed the last version, inserted my cred and can browse succesfully. But when it's time to play something it crash

```
Traceback (most recent call last):
  File "/home/self/.local/bin/jellyfin-cli", line 8, in <module>
    sys.exit(app())
  File "/home/self/.local/lib/python3.8/site-packages/jellyfin_cli/main.py", line 194, in __call__
    return self._run()
  File "/home/self/.local/lib/python3.8/site-packages/jellyfin_cli/main.py", line 191, in _run
    self.draw.run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.8/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/usr/lib/python3.8/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/home/self/.local/lib/python3.8/site-packages/jellyfin_cli/main.py", line 171, in _bg_play
    await self.player._play(item, block=False)
  File "/home/self/.local/lib/python3.8/site-packages/jellyfin_cli/utils/play_utils.py", line 72, in _play
    key = await self._get_api_key()
  File "/home/self/.local/lib/python3.8/site-packages/jellyfin_cli/utils/play_utils.py", line 32, in _get_api_key
    if "jellyfin_cli_play" in keys:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by marios8543** [comment]
Hmm it seems like something goes wrong when it tries to fetch the API keys. I will look into it later today

**Comment by marios8543** [comment]
Is the user you are logging in from an admin ? This app generates a new API key on playback for safety reasons, instead of using the one tied to your account so obviously your account needs to be able to create tokens in order to play. I will make this optional if it proves to be a problem

**Comment by chmol** [comment]
it's not admin, regular user -   I try to keep privileges separated.

if I understand well, users cannot create such token?

**Comment by marios8543** [comment]
Yes, users without permissions to manage the server cannot create or view API tokens. If you login with an admin user it will work. I will fix this later today to make it compatible with non-admin users as well.

**Comment by marios8543** [comment]
Fixed. Update to the latest version
65c741b35584b214b38cf8c575b97bec015560ff

**Comment by chmol** [comment]
damn you're fast ! Thanks !
