### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by gerroon** [marios8543/Jellyfin-CLI#2]
HI 

I just tried this on Debian testing against Jellyfin  10.5.2 on Debian Testing 

```

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe3444d8890>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe3444d8950>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fe344552ec0>, 524018.875663425)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fe3444d8ad0>
Logged in...
Traceback (most recent call last):
  File "/usr/local/bin/jellyfin-cli", line 10, in <module>
    sys.exit(app())
  File "/home/USER/.local/lib/python3.7/site-packages/jellyfin_cli/main.py", line 226, in __call__
    return self._run()
  File "/home/USER/.local/lib/python3.7/site-packages/jellyfin_cli/main.py", line 223, in _run
    self.draw.run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/usr/local/lib/python3.7/dist-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/home/USER/.local/lib/python3.7/site-packages/jellyfin_cli/main.py", line 83, in _draw_home
    views = await self.client.get_views()
  File "/home/USER/.local/lib/python3.7/site-packages/jellyfin_cli/jellyfin_client/JellyfinClient.py", line 73, in get_views
    return [View(i, self.context) for i in res["Items"]]
  File "/home/USER/.local/lib/python3.7/site-packages/jellyfin_cli/jellyfin_client/JellyfinClient.py", line 73, in <listcomp>
    return [View(i, self.context) for i in res["Items"]]
  File "/home/USER/.local/lib/python3.7/site-packages/jellyfin_cli/jellyfin_client/data_classes/View.py", line 15, in __init__
    if res["CollectionType"] == "movies":
KeyError: 'CollectionType'

```

**Comment by marios8543** [comment]
hmm this is a weird one. could you give me a bit more information about your setup, what kind of libraries you have and if your user is admin or not

**Comment by gerroon** [comment]
My user is admin. I have all kinds of mixed libraries like movies, music etc.

**Comment by marios8543** [comment]
hmm it appears that i have not accounted for mixed type libraries. thanks for reporting it. i will fix it as soon as possible

**Comment by marios8543** [comment]
@gerroon fixed. update to the latest version. that being said i really don't recommend using mixed content libraries as they tend to be very unpredictable and problematic.
c2bf240e40dc010f2c5a603d30628efd4c8624f1
